# Generated by Django 4.0.3 on 2022-06-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='is_read_by_admin',
            field=models.BooleanField(default=False, verbose_name='is read by admin?'),
        ),
    ]
