# Generated by Django 4.0.3 on 2022-07-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_profile_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_images',
            name='image',
            field=models.ImageField(upload_to='uploaded_files'),
        ),
    ]
