# Generated by Django 4.0.3 on 2022-05-18 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='title of subject')),
                ('url_title', models.CharField(db_index=True, max_length=300, verbose_name='title of url')),
                ('is_active', models.BooleanField(verbose_name='is active/not active')),
                ('is_deleted', models.BooleanField(verbose_name='deleted/undeleted')),
            ],
            options={
                'verbose_name': 'Meta_product_category',
                'verbose_name_plural': 'Meta_plural_categories',
            },
        ),
        migrations.CreateModel(
            name='product_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=300, null=True, verbose_name='prod_info_color')),
                ('size', models.CharField(max_length=200, null=True, verbose_name='prod_info_size')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='title')),
                ('price', models.IntegerField(verbose_name='price')),
                ('description', models.TextField(db_index=True, verbose_name='main_description')),
                ('short_description', models.CharField(db_index=True, max_length=390, null=True, verbose_name='short-description')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active/not_active')),
                ('slug', models.SlugField(blank=True, default='', max_length=300, unique=True)),
                ('is_deleted', models.BooleanField(verbose_name='deleted/undeleted')),
                ('category', models.ManyToManyField(related_name='product_category', to='products.product_category', verbose_name='categories')),
            ],
        ),
        migrations.CreateModel(
            name='product_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(db_index=True, max_length=300, verbose_name='tags-and-caption')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='products.products')),
            ],
            options={
                'verbose_name': 'tag',
            },
        ),
    ]
