# Generated by Django 4.0.3 on 2022-05-23 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='brand_name')),
                ('is_active', models.BooleanField(verbose_name='active/not_active')),
            ],
            options={
                'verbose_name': 'barnd_name',
                'verbose_name_plural': 'brands_name',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_brand', verbose_name='brand_name_product'),
        ),
    ]
