# Generated by Django 4.0.3 on 2022-07-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_brand_products_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploadedfiles/products', verbose_name='picture'),
        ),
    ]
