# Generated by Django 4.0.3 on 2022-05-12 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=300, verbose_name='color')),
                ('size', models.CharField(max_length=200, verbose_name='size')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='product_infos',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_info', to='products.product_info', verbose_name='additional_infos'),
        ),
    ]
