# Generated by Django 4.0.3 on 2022-05-12 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_info_products_product_infos'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99)),
            ],
            options={
                'verbose_name': 'tag',
            },
        ),
        migrations.AlterModelOptions(
            name='product_category',
            options={'verbose_name': 'Meta_product_category', 'verbose_name_plural': 'Meta_plural_categories'},
        ),
        migrations.AlterField(
            model_name='product_info',
            name='color',
            field=models.CharField(max_length=300, null=True, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='product_info',
            name='size',
            field=models.CharField(max_length=200, null=True, verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_infos',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_info', to='products.product_info', verbose_name='additional_infos'),
        ),
        migrations.AddField(
            model_name='products',
            name='tag',
            field=models.ManyToManyField(blank=True, to='products.product_tag'),
        ),
    ]
